---
services:
  proxy:
    restart: always
    image: nginx
    container_name: proxy
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  db:
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: hack
    container_name: db
    image: mysql:8.4
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - my_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "5555:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: frontend
    networks:
      - my_network
    ports:
      - 3000:80

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8085:8085
    networks:
      - my_network
    volumes:
      - .:/app

  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=123456789
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_volume:
  minio-data: {}
